name: smirk
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
  - pytorch3d
dependencies:
  - python=3.9
  - pip
  - pytorch>2.1.1,<2.3.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - ca-certificates
  - openssl
  - ipykernel
  - certifi
  - pytorch3d
  - pip:
    - albumentations==1.3.0
    - mediapipe==0.10.10
    - numpy==1.22.4
    - omegaconf==2.3.0
    - opencv_contrib_python==4.9.0.80
    - opencv_python==4.9.0.80
    - opencv_python_headless==4.9.0.80
    - scikit_learn==1.3.2
    - scikit-image==0.22.0
    - timm==0.9.16
    - tqdm==4.66.2
    - chumpy==0.70
    - gdown
    - fvcore
    - iopath
    - pytorch_lightning==2.2.1
    - pandas==2.2.2
